/** @type {import('tailwindcss').Config} */
export default {
  darkMode: 'class',
  // Preflight is disabled to avoid resetting Element Plus component styles that
  // are still used on some pages. A scoped reset lives in src/assets/tailwind.css.
  corePlugins: { preflight: false },
  content: ['./index.html', './src/**/*.{vue,js,ts,jsx,tsx}'],
  theme: {
    extend: {
      colors: {
        primary: '#00488d',
        'on-primary': '#ffffff',
        'primary-container': '#005fb8',
        'on-primary-container': '#cadcff',
        'primary-fixed': '#d6e3ff',
        'primary-fixed-dim': '#a8c8ff',
        'on-primary-fixed': '#001b3d',
        'on-primary-fixed-variant': '#00468b',
        'inverse-primary': '#a8c8ff',
        secondary: '#a43d00',
        'on-secondary': '#ffffff',
        'secondary-container': '#fc6712',
        'on-secondary-container': '#551c00',
        'secondary-fixed': '#ffdbcd',
        'secondary-fixed-dim': '#ffb597',
        'on-secondary-fixed': '#360f00',
        'on-secondary-fixed-variant': '#7d2d00',
        tertiary: '#005503',
        'on-tertiary': '#ffffff',
        'tertiary-container': '#007006',
        'on-tertiary-container': '#8cf27a',
        'tertiary-fixed': '#94fa81',
        'tertiary-fixed-dim': '#79dd68',
        'on-tertiary-fixed': '#002200',
        'on-tertiary-fixed-variant': '#005303',
        error: '#ba1a1a',
        'on-error': '#ffffff',
        'error-container': '#ffdad6',
        'on-error-container': '#93000a',
        background: '#faf9f8',
        'on-background': '#1a1c1c',
        surface: '#faf9f8',
        'on-surface': '#1a1c1c',
        'surface-variant': '#e3e2e1',
        'on-surface-variant': '#424752',
        'surface-tint': '#005db5',
        'surface-bright': '#faf9f8',
        'surface-dim': '#dadad9',
        'surface-container-lowest': '#ffffff',
        'surface-container-low': '#f4f3f2',
        'surface-container': '#efeeed',
        'surface-container-high': '#e9e8e7',
        'surface-container-highest': '#e3e2e1',
        outline: '#727783',
        'outline-variant': '#c2c6d4',
        'inverse-surface': '#2f3130',
        'inverse-on-surface': '#f1f0ef',
      },
      borderRadius: {
        DEFAULT: '0.125rem',
        lg: '0.25rem',
        xl: '0.5rem',
        full: '0.75rem',
      },
      spacing: {
        'stack-gap': '24px',
        'gutter-table': '16px',
        'component-gap': '12px',
        'sidebar-width': '260px',
        'container-padding': '32px',
      },
      fontFamily: {
        sans: ['Inter', 'sans-serif'],
        'table-data': ['Inter'],
        'headline-md': ['Inter'],
        'label-upper': ['Inter'],
        'display-lg': ['Inter'],
        'body-sm': ['Inter'],
        'title-sm': ['Inter'],
        'body-md': ['Inter'],
      },
      fontSize: {
        'table-data': ['14px', { lineHeight: '20px', fontWeight: '400' }],
        'headline-md': ['24px', { lineHeight: '32px', fontWeight: '600' }],
        'label-upper': ['12px', { lineHeight: '16px', letterSpacing: '0.05em', fontWeight: '600' }],
        'display-lg': ['32px', { lineHeight: '40px', letterSpacing: '-0.02em', fontWeight: '700' }],
        'body-sm': ['13px', { lineHeight: '18px', fontWeight: '400' }],
        'title-sm': ['18px', { lineHeight: '24px', fontWeight: '600' }],
        'body-md': ['14px', { lineHeight: '20px', fontWeight: '400' }],
      },
    },
  },
  plugins: [],
};
